### ISSUE TITLE
Xarray_filters Quarter 3, 2017 Priorities

### ISSUE THREAD

**Issue by PeterDSteinberg** [ContinuumIO/xarray_filters#28]
## Xarray_filters Quarter 3, 2017 Priorities
Let's address the checklist below in approximately the order shown, aiming to get this list done by AGU December.
### Docs / cleanup / promotion of Elm and related tools
 * [ ] Create docs for xarray_filters https://github.com/ContinuumIO/xarray_filters/issues/21
 * [ ] Consolidate examples #24
 * [ ] Create a notebook where parts of the row dimension MultiIndex become features #23
### Bugs:
 * [ ] from_features is broken if rows are dropped after to_features #27
 * [ ] Usage of `inspect` module in elm/earthio/xarray_filters #12 
### Related to data structure flexibility [long term epic 202](https://github.com/ContinuumIO/elm/issues/202):

The following are related to synthetic data set generation:
 * [ ] Default arguments for xarray_filters.datasets.make_* functions #17
 * [ ] Add more domain specific transformations to XyTransformer #6
 * [ ] Support remaining sklearn make_* simulation functions deferred #5
 * [ ] Use the new datashader regridding tools when available deferred #1

And support for `FeatureUnion` based on dask will speed up many workflows:
 * [ ] Parallelism of `FeatureUnion` for xarray_filters #22 - We can use the notebook creation to experiment with FeatureUnion from `daskml` (formerly the `FeatureUnion` of dask-searchcv)

cc @gbrener @hsparra

**Comment by gbrener** [comment]
Quick note - I added #29 to address dev package uploading from successful CI builds. Not sure how/if it works into these bullets priority-wise.

**Comment by PeterDSteinberg** [comment]
Agreed #29 is something we need soon - lack of CI build upload in xarray_filters is causing corresponding Elm CI problems.

**Comment by gbrener** [comment]
@PeterDSteinberg - since this checklist was created, there have been additional issues created. Do we want to update the checklist to reflect these issues? Or would you prefer I focused on other priorities?

**Comment by PeterDSteinberg** [comment]
Let's keep it updated for things like the specific documentation or bugs we discuss fixing before AGU December, e.g. #41 .
